name: Reusable Workflow
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        type: string
        default: "18.x"

      npm-install-command:
        description: "Npm command to run for building the application"
        required: true
        type: string
        default: "ci"

      run-playwright:
        description: "Run Playwright tests"
        required: false
        type: boolean
        default: true

      upload-artifact:
        description: "Enable artifact upload"
        required: false
        type: boolean
        default: true

    secrets:
      USERNAME:
        description: Username for testing
        required: false
      PASSWORD:
        description: Password for testing
        required: false

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ${{ inputs.npm-install-command }}

      - name: Install Playwright Browsers
        if: ${{ inputs.run-playwright }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ inputs.run-playwright }}
        run: npx playwright test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload Artifacts
        if: ${{ inputs.upload-artifact == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
